# MurderRun Configuration File

# Sets the language for the plugin
# Valid options are: EN_US, ZH_CN
# Default is EN_US
language: EN_US

# Sets the method to host the pack that is used by the plugin
# Valid options are MC_PACK_HOSTING, LOCALLY_HOSTED_DAEMON
# Default is MC_PACK_HOSTING

# MC_PACK_HOSTING will upload the pack on https://mc-packs.net/ and cache the pack link
# This option doesn't require port-forwarding, but may be limited by web requests

# LOCALLY_HOSTED_DAEMON will start a local daemon that will host the pack using the below options
# This option requires port-forwarding to work properly
pack-provider: MC_PACK_HOSTING

# If using LOCALLY_HOSTED_DAEMON, the below options will be used
server:

  # The host name of the daemon (for example: google.com)
  # Default is localhost
  host-name: localhost

  # The port of the daemon (for example, 7270)
  # Default is 7270
  port: 7270

  # With this configuration, the final pack link will be: http://localhost:7270/

# The data provider to use to store all plugin data
# Valid options are JSON and SQL. If you are using SQL, make sure to the configuration below
# to match your SQL database.
# default is JSON
relational-data-provider: JSON

# Represents the database options
database-options:

  # The driver you want to use (only Hibernate supported drivers)
  # Default is org.h2.Driver
  driver: org.h2.Driver

  # Database JDBC url to connect to
  # Default is jdbc:h2:~/test
  jdbc-url: jdbc:h2:~/test

  # Database name for the plugin
  # Default is murderrun
  database-name: murderrun

  # Hibernate internal option
  # Default is update
  hbm2ddl: create

  # Database username to connect
  # Default is prod
  username: prod

  # Database password to connect
  # Default is prod
  password: prod

  # Show SQL statements in the console
  # Default is true
  show-sql: true

