# MurderRun Configuration File

# Sets the method to host the pack that is used by the plugin
# Valid options are MC_PACK_HOSTING, LOCALLY_HOSTED_DAEMON

# MC_PACK_HOSTING will upload the pack on https://mc-packs.net/ and cache the pack link
# This option doesn't require port-forwarding, but may be limited by web requests

# LOCALLY_HOSTED_DAEMON will start a local daemon that will host the pack using the below options
# This option requires port-forwarding to work properly
pack-provider: MC_PACK_HOSTING

# If using LOCALLY_HOSTED_DAEMON, the below options will be used
server:

  # The host name of the daemon (for example: google.com)
  host-name: localhost

  # The port of the daemon (for example, 7270)
  port: 7270

  # With this configuration, the final pack link will be: http://localhost:7270/

# The data provider to use to store all plugin data
# Valid options are JSON and SQL. If you are using SQL, make sure to the configuration below
# to match your SQL database.
relational-data-provider: JSON

# Represents the database options
database-options:

  # The driver you want to use (only Hibernate supported drivers)
  driver: com.mysql.cj.jdbc.Driver

  # Database JDBC url to connect to
  jdbc-url: jdbc:h2:~/test

  # Database name for the plugin
  database-name: 'murderrun'

  # Hibernate internal option
  hbm2ddl: 'update'

  # Database username to connect
  username: 'prod'

  # Database password to connect
  password: 'prod'

  # Show SQL statements in the console
  show-sql: true

