version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m -Xms2600m
    executor: java
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2/
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs/MurderRun-1.21.1-v1.0.0-all.jar